### ISSUE TITLE
Remove Neighbouring Vertex + conjugate in "def display_keys_to_modify"

### ISSUE THREAD

**Issue by rpeky** [rpeky/SUTD_Map_project#10]
"def display_keys_to_modify"
To add an additional function: self.remove_existing_neighbour

Features:
1) Display existing neighbours in this vertex and index them using {:02d}\t{} format as per other functions 
2) Query for index of neighbour to be removed, use 'q' to escape this and return to display_keys_to_modify as an additional escape condition
3) Remove the neighbour from this vertex
4) Remove this vertex from neighbour (the conjugate - since it does not make sense that two points are not bi-directional in our usecase)
5) Display current state of neighbours, query to continue ( or automatically escape to either display_keys_to_modify or graph_generation_tool if no neighbours to remove)

**Comment by thelollipopman** [comment]
Please correct me if I'm wrong, but I think there is already a remove_existing_neighbours function. Although it currently uses the keywords in selection_no rather than 'q' to break out of the loop and return to display_keys_to_modify
